### ISSUE TITLE
Game freezes on clicking in another merc after seeing the Robot inventory UI

### ISSUE THREAD

**Issue by joaogdcordeiro** [1dot13/source#126]
![Animation](https://user-images.githubusercontent.com/32676717/220512019-42703723-8846-4d1f-ae3e-3b3fe4118947.gif)

The game freezes forever without any error when I press another merc like "hummer" or "Ira":

Version:
![image](https://user-images.githubusercontent.com/32676717/220512266-2dc2a036-5bfd-42d4-bffb-e2e30f371dea.png)

**Comment by joaogdcordeiro** [comment]
This is probably related to a minor bug when if the vehicles inventory having an issue in strategic screen:
![Animation](https://user-images.githubusercontent.com/32676717/220513993-835a2e1d-9dca-4525-83a3-95c5d46e3e90.gif)

**Comment by rftrdev** [comment]
@joaogdcordeiro can you attach a save file?

**Comment by joaogdcordeiro** [comment]
[QuickSave.zip](https://github.com/1dot13/source/files/10799807/QuickSave.zip)

Here

**Comment by rftrdev** [comment]
I can't repro the behaviour in your images above. Can you try updating these files in your `Data/Interface` (Not Data-1.13) directory?
https://github.com/1dot13/gamedir/blob/master/Data/Interface/MAPINV_800x600.sti
https://github.com/1dot13/gamedir/blob/master/Data/Interface/MAPINV_1024x768.sti

**Comment by rftrdev** [comment]
Should be fixed with #127!
