### ISSUE TITLE
Inactive Militia no longer parttakes in fights

### ISSUE THREAD

**Issue by kitty624** [1dot13/source#150]
If there is Militia at map and enemy attacks,

the Militia will just stand at initial place doing nothing

alt+rmb shows they carry weapons

unchanged settings, so no militia equipment involved

they won't hide, flee, attack ... standing there, getting surpressed, cowering in fear and eventually got hit and die

only exception is militia that early on got an interrupt, those will parttake in rest of fight as well

i got a message about ai-deadlock

![militia not active](https://github.com/1dot13/source/assets/58940527/14caa2b1-1289-4664-a3e3-153e0dcf006d)

**Comment by Asdow** [comment]
This may have been fixed with the #156 commit. Report back if the behavior still persists.

**Comment by rftrdev** [comment]
Potentially fixed by #171, but this only affects militia. We should open another issue for bloodcats
