### ISSUE TITLE
Run as Administrator

### ISSUE THREAD

**Issue by ph-hoffmann** [1dot13/source#170]
Why does the JA2.exe has an "run as Administrator" flag? I would prefer not to grant administrator rights to applications if not absolutely necessary.

**Comment by Asdow** [comment]
It's not? At least not in our English release that I downloaded and checked as a test.

**Comment by Asdow** [comment]
I'm closing this as the executable in our release doesn't have "run as admin" flag on by default, at least in English localization. If the issue happens in some other language, please report back.
