### ISSUE TITLE
Assertion Failure Runtime Error Bug

### ISSUE THREAD

**Issue by TwisTonFire** [1dot13/source#179]
Assertion Failure [Line 1128 in file D:\a\source\Tactical\Arms Dealer Init.cpp]

GetArmsDealerItemTypeFromItemNumber(), invalid class 0 for item 1762 gMAXITEMS_READ = 1763

This error keeps showing up just by passing time in the first 20 days.

German Patchfile -> All 1.13 content overrided and disabled (with ingame options)

My Squad: I.M.P Soldier ( Arms Dealer Background ) , IRA, Dimitri

**Comment by Asdow** [comment]
Do you have a save game that consistently replicates it? We've gotten reports of this from several users, but gMAXITEMS_READ is written to only once, when the items.xml is loaded by the game and none of us coders have been hit with this bug.
