### ISSUE TITLE
Militia Screen Bug at 720p

### ISSUE THREAD

**Issue by Sardaukai** [1dot13/source#190]
Hi all,
maybe there is a fix already or a kind of a workaroud. 
Well it is only a "compfort" thing but if you are able to fix that it would be great!!

Problem, simply look at the screenshot. Militia display is wrong...

![MilitiaScreenBug](https://github.com/1dot13/source/assets/23153279/8c664d8f-3e6d-4fe2-8bf7-3490da69e9f5)

I play with version JA2_113-v0-3997-ga0ac81-G0f38Ld66a-German
Resoluiton is 720p, if I change to higher it works but I loose the squad table and only see merc's inventory....

PS: 
Finally I want to thank you for your work here!   
1.13 is great!

**Comment by rftrdev** [comment]
@Asdow when you're free :)
