### ISSUE TITLE
ALLOW_TUNNEL_VISION = FALSE in ja2options produces memory allocation errors

### ISSUE THREAD

**Issue by dpapadam** [1dot13/source#34]
When setting this feature to FALSE in ja2options.ini and equipping binocs, the LOS goes on forever so when you scroll to the border of the map it produces a memory allocation error (see screenshot)

Error should be rather easy to replicate:

1. Set ALLOW_TUNNEL_VISION = FALSE in ja2options
2. Start game, equip binocs
3. Hold down END (Line of Sight) and scroll to the border of the map

The merc's LOS is about 2 screen lengths to the left that's how far this is..

Note: The map in the screenshot is 200x200
![memory alloc error](https://user-images.githubusercontent.com/58604696/204134988-4b81e9af-8eec-4ff5-8da7-fd1fe8011585.png)

**Comment by Asdow** [comment]
Can't replicate on default 1.13. Tunnelvision off and equipping binoculars results in a narrow but long vision cone and no assertion errors come up. Second screenshot with binoculars unequipped

![jagged_alliance_2-2022-12-25-21_57_37](https://user-images.githubusercontent.com/20314541/209480581-8cf6015e-5049-4d71-919c-95a6d20f5d81.png)
![jagged_alliance_2-2022-12-25-21_57_45](https://user-images.githubusercontent.com/20314541/209480584-20db4d8a-2b89-49ce-8c5d-2d311b960b5b.png)

**Comment by dpapadam** [comment]
Hello,

Perhaps this is a bug on bigger maps ? This is occurring on my 200/200 map

**Comment by Asdow** [comment]
Tried it on AIMNAS big maps and still the same result. No errors

**Comment by dpapadam** [comment]
Ok thank you very much Asdow, perhaps this was correct in one of the newer releases ? I will test it again once I update to the newer source. I'll open a new ticket if necessary.
