### ISSUE TITLE
ItemFlag placement in items.xml can deny functionalty of Molle-pouches

### ISSUE THREAD

**Issue by kitty624** [1dot13/source#358]
If an item is a MOLLE-pouch and does have an ItemFlag, it matters where the tag is placed in Items.xml

if the ItemFlag-tag is below the Attachment-tag, the pouch can't be attached to a Molle-carrier (i.e., a leg-rig)

Attachment>1</Attachment
ItemFlag>2147483648</ItemFlag

if the ItemFlag-tag is above the Attachment-tag, it can be attached

ItemFlag>2147483648</ItemFlag
Attachment>1</Attachment

Tested with different ItemFlags, same result

**Comment by Asdow** [comment]
> when I use ItemFlag**2** as tag, instead of ItemFlag (i.e., `<ItemFlag2>2147483648</ItemFlag2>`) , it doesn't matter where in order (above/below attachment-tag) the flag is but that tag isn't in xml (in gamedir) and going by ItemTypes.h, it isn't a ItemFlag2 ?


ItemFlag2 bitfields are stored as separate tags in the xml. It was done to preserve compatibility with our existing xml files, and is more readable for modders than <ItemFlags2>long integer value<ItemFlags2>

When the item xml data is read into the game, tags such as <Crowbar>0</Crowbar> gets translated into a bitfield value in the UINT64 ItemFlags2 field that the game uses internally.

A tag like <Itemflag2> is never read from the xml files, so when you changed the tag, it was equivalent to deleting the whole <ItemFlag> tage from the xml file
