### ISSUE TITLE
wrong name ja2 executable in SCI

### ISSUE THREAD

**Issue by tais** [1dot13/source#36]
it seems the executable in the SCI's has the wrong name, this should be named ja2.exe to make sure it overwrites the original JA2 executable, people will run into issues staring the old exe and get confused if this file is not overwritten.

**Comment by rftrdev** [comment]
I'll update the build action, and add a readme with version info instead of putting that into the filename

**Comment by rftrdev** [comment]
@kitty624 - what would be the ideal change to the output to make things easy for you? Keep the existing .exe outputs and add a plain "ja2.exe"? I can also generate a text file with both source and gamedir version info.

**Comment by rftrdev** [comment]
How's this: rename the output exes to "ja2.exe", "ja2ub.exe", and "ja2mapeditor.exe", and add a version info text file that looks something like this:

> If you encounter problems during gameplay, please give the following version information:
  Source SHA: <latest source commit hash; eg 48f3476>
  Source Date: <latest source commit date; eg 20221203>
  Gamedir SHA: <latest gamedir commit hash; eg 46486599>
  Gamedir Date: <latest gamedir commit date; eg 20221110>

What else would be good/useful to include in the text file? And any preference on a file name?

**Comment by rftrdev** [comment]
Committed with #40
