### ISSUE TITLE
Map editor doesnt print roads properly in big maps

### ISSUE THREAD

**Issue by edawgsnizzle** [1dot13/source#368]
When making roads in a map larger than 160x160, roads dont print properly and are missing tiles
![Map Editor Issue](https://github.com/user-attachments/assets/cedfbbbb-2113-4636-9fc5-e46404b20dad)

**Comment by edawgsnizzle** [comment]
![image](https://github.com/user-attachments/assets/70675d37-168a-4f4d-8660-2c4eae4d442a)
looks like it misplaces the textures in the wrong coordinates.

**Comment by Asdow** [comment]
I can't seem to be able to replicate this. Is it related to some specific tileset?

**Comment by Asdow** [comment]
How big are big maps? 300x300 tile map gave me no issues

**Comment by edawgsnizzle** [comment]
Other than what ive provided i dont know what else i can say. For me it happens on any map bigger than 160x160. Even 168x168 gave me that issue.

**Comment by Asdow** [comment]
Okay, it's this tile and it's repeateable in both regular and UB mapeditor. Any map size over 160 x 160 causes the glitch.  Oddly enough, already placed road tiles do not glitch.

![kuva](https://github.com/user-attachments/assets/179b7d38-89d0-463a-b652-bfb5e3549504)

**Comment by edawgsnizzle** [comment]
Just making sure, it was both of the tiles that make up the bend not just 1
