### ISSUE TITLE
Merc annimation missing when running with hand mortar

### ISSUE THREAD

**Issue by edawgsnizzle** [1dot13/source#384]
Running with the hand mortar in-hand has missing animation. standing and walking are fine though
![ja2a](https://github.com/user-attachments/assets/e37c8105-e039-462b-92e6-24c5d4e6a3ae)

**Comment by Asdow** [comment]
Fixed in gameDir commit https://github.com/1dot13/gamedir/commit/a148f8f633ba7c60e8bd8b741d344966b9ad0dda
