### ISSUE TITLE
BOOLEAN	fExplodeOnImpact in EXPLOSIVETYPE is unused

### ISSUE THREAD

**Issue by Asdow** [1dot13/source#46]
Could be removed from the code and subsequent .xml file as it's not used anywhere in the code.

**Comment by tais** [comment]
In code or just in XML files, because if it is code functional it could mean mods use it?

**Comment by Asdow** [comment]
Would have to search through the codebase if there is any commented out functionality related to it, but for now we only read the value from xml if it exists and then do absolutely nothing with it.

**Comment by Asdow** [comment]
Seems it is used in the code after all, but my VS is not showing the references correctly. Thanks Kitty for looking into it.
