### ISSUE TITLE
explosions that collapse roofs result in white fire retardant smoke spreading

### ISSUE THREAD

**Issue by kitty624** [1dot13/source#50]
If any explosion is strong enough to collapse roof, in addition to debris smoke, there is also white smoke added.
This is the white smoke of the fire extinguisher and is fire retardant.
Happens indoor, but result will happen also if initial explosion happen outdoor (outside wall of room).
Tested with action items, tnt, hmx, c1, c4 and mk2-grenade. As long as it results in roof collapse, we get fire retardant smoke in the room below the roof.

This isn't only looking ugly, since the smoke is fire retardant and blinding it interferes with other things we may wanna do.
This further hinders to add any new explosive with changed smoke effect. if we don't know the reason for this, we can't be sure that dsired new effect would happen as well.

Tried to look into this, but as far as i can tell, when the white smoke was added (r9141/g2602) nothing regarding roofs or indoor was changed (afaik).

**Comment by Asdow** [comment]
Should be fixed now, via gamedir commit 1e140721ac1ed9039e6c9f0582be2dbef5ae579d
