### ISSUE TITLE
tooltips broken on boby rays shop and on aim and merc inventories on items

### ISSUE THREAD

**Issue by Parkan1986** [1dot13/source#57]
There is a bug with tooltip about items in boby rays and in aim and merc characters inventory.for example boby ray descriptions of items will be a weapon which were last on previus page and will be show on other items after last weapon.same for aim  inventory on aim site after weapons other items like lbe will be named like a weapon.tested on plain 1.13 and brainmod. 

![jagged_alliance_2-2022-12-28-01_14_25](https://user-images.githubusercontent.com/30984138/209727603-1abd35ad-d478-4845-815d-9ed0a1e1adcd.png)
![jagged_alliance_2-2022-12-28-01_14_35](https://user-images.githubusercontent.com/30984138/209727607-7819a50d-9c4f-487c-8d57-2b0917547c29.png)
![jagged_alliance_2-2022-12-28-01_14_50](https://user-images.githubusercontent.com/30984138/209727613-8403e2a4-d7d1-4af3-94a0-26635059e914.png)

**Comment by Asdow** [comment]
Can't replicate. No matter how I browse the websites, the tooltips update correctly.
