### ISSUE TITLE
Strategic map in JA2UB shows sector names from JA2

### ISSUE THREAD

**Issue by majcosta** [1dot13/source#63]
check screenshots:
![2023-01-04_04-38-47](https://user-images.githubusercontent.com/34732933/210506759-b42e7a91-d824-435c-a7e8-89e8a3bdafbe.png)
![2023-01-04_04-39-01](https://user-images.githubusercontent.com/34732933/210506777-05f170ac-407b-4295-be30-f65c6839f6c5.png)

**Comment by Asdow** [comment]
Added the issue to gamedir repo
