### ISSUE TITLE
General mode doesn't work properly, DEADLOCK error when general trying to flee the battle

### ISSUE THREAD

**Issue by MeshVoid** [1dot13/source#73]
BUILD VERSION:
sc 7a0a567
gc  4648659

So, apparently, when you enable Generals in Ja2_Options.INI file or in override options of the game of the latest build you witness that Generals mode is not working as intended and returns errors to player and takes very long to process enemy turns (some people complained on discord that the game freezes forever) until it prints out the error message.

To replicate the error do the following:
1. Launch the game with Generals settings turned on. 
2. Make sure that general appeared in Omerta, so that you could spawn directly in the location where General is spawned. 
3. Alert the General's crew, witness error and fleeing attempt, the indefinite infamous clock animation

Attached a screenshot of the error and log files, also my ini file. 

![jagged_alliance_2-2023-01-12-08_19_47](https://user-images.githubusercontent.com/35863328/211962264-2f3161c6-94e2-4ebc-96af-f7ce2b224a13.png)

[ERROR_REPORT.iniErrorMessages.txt](https://github.com/1dot13/source/files/10397648/ERROR_REPORT.iniErrorMessages.txt)
[LiveLog.txt](https://github.com/1dot13/source/files/10397650/LiveLog.txt)

**Comment by Asdow** [comment]
I've had this happen with regular enemies as well, where they would deadlock trying to flee and would stay put. It's probably not limited to generals, but those might just be more inclined to attempt to flee a battle.

**Comment by MeshVoid** [comment]
> I've had this happen with regular enemies as well, where they would deadlock trying to flee and would stay put. It's probably not limited to generals, but those might just be more inclined to attempt to flee a battle.

Affirmative, this is related to retreating mechanic in general, encountered same errors when it happened with ordinary enemies in game later on too when played with turned on enemy retreat feature in .ini file.

**Comment by themaster567** [comment]
This is not fixed in any fashion whatsoever and should be reopened immediately.
