### ISSUE TITLE
Remove Artificial Merc Lights

### ISSUE THREAD

**Issue by rftrdev** [1dot13/source#84]
Bonus points for adding a way to briefly highlight or ping player mercs as a replacement for artificial lights

**Comment by majcosta** [comment]
Replace "Merc lights during movement" with "Artificial merc lights" option, but defaulting to 'off' instead
'G' key behavior remains unaltered.

**Comment by dpapadam** [comment]
Nooo please don't remove fakelights ! I use them for making bullets pretty. Fakelights allows the bullet lighting to remaining aesthetic without affecting the battlefield.

Also when NOT fakelights it actually destroys the merc's LOS

**Comment by majcosta** [comment]
fake lights aren't getting removed, just that fake light around the merc as he's walking around is defaulting to false instead of true. you can still turn it on by pressing 'G'

**Comment by majcosta** [comment]
got in with #86, you can close this
